server:
  port: 9000

spring:
  application:
    name: cloudberry
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cloudberry-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          trusted.packages: '*'
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cloudberry
  influx2:
    url: http://localhost:9999/
    username: root
    password: ziemniak
    bucket: cloudberry-logs
  profiles:
    active: influx

influx:
  organization-name: cloudberry
  buckets:
    default-logs: cloudberry-logs
    default-logs-meta: cloudberry-logs-meta

---

spring:
  profiles: prod
  kafka:
    bootstrap-servers: kafka-cb:29092
  data:
    mongodb:
      host: cloudberry-cb

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: localhost:9092

---

spring:
  profiles: olgierd
  influx2:
    org: 05e9e0b3c3a37000
    token: W5lZySDF5A1XevbKqIK717PHBxZOD-D0pSkwYu--LmmVYudgPMGJ-a-oOVVjDl_tgjASZ1efAtGZkV6FbVIYUQ==

---

spring:
  profiles: michal
  influx2:
    org: 05dce0dac762f000
    token: r6FvmGQ-L1yV0zrGF8raLY43RlUrvlxE-EOdmfnqGbb2ZmPHHS23UnDshzh6d7iFYV3tGL9H5X9YkT0KKhhxjw==
