server:
  port: 9000

spring:
  application:
    name: cloudberry
  kafka:
    consumer:
      group-id: cloudberry-group
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cloudberry

---

spring:
  profiles: prod
  kafka:
    bootstrap-servers: kafka-cb:29092

---

spring:
  profiles: dev
  #... just mocks to not forget how to use those xd
