server:
  port: 9000

spring:
  application:
    name: cloudberry
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cloudberry-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          trusted.packages: '*'
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cloudberry
  influx2:
    url: http://localhost:9999/
    username: root
    password: ziemniak
    org: 05d2d61891515000 # local value, todo
    bucket: cloudberry
    token: 0e-7IP88YUpOX-oIYn53ycuriV4TRekD20Kd-4uoKhXyZiBRVoEBs9YuI9XotRk6s4BL2wVIW0lwVG9tTYNj7w==  # local value, todo

---

spring:
  profiles: prod
  kafka:
    bootstrap-servers: kafka-cb:29092
  data:
    mongodb:
      host: cloudberry-cb

---

spring:
  profiles: dev
  kafka:
    bootstrap-servers: localhost:9092
