server:
  port: 9000

spring:
  application:
    name: cloudberry
  kafka:
    consumer:
      group-id: cloudberry-group
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cloudberry
