version: '2'

networks:
  kafka-network:
    driver: bridge

services:
  zookeeper-server:
    image: bitnami/zookeeper:latest
    hostname: zookeeper-server
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka-server:
    image: bitnami/kafka:latest
    hostname: kafka-server
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENERS: LISTENER_DOCKER://kafka-server:29092,LISTENER_OUT://kafka-server:9092
      # te dwa są do lokalnego startowania spring boota
      #      KAFKA_ADVERTISED_HOST_NAME: localhost
      #      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka-server:29092,LISTENER_OUT://localhost:9092
      # te dwa są do startowania spring boota z dockera
      KAFKA_ADVERTISED_HOST_NAME: kafka-server
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka-server:29092,LISTENER_OUT://kafka-server:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_OUT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100