version: '2'

networks:
  monitoring:

services:
  # todo - migrate from beta: https://docs.influxdata.com/influxdb/v2.0/reference/rc0-upgrade-guide/
  influxdb-cb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    hostname: influxdb-cb
    container_name: influxdb-cb
    ports:
      - 9999:9999
    volumes:
      - /data/cloudberry/influxdbv2:/root/.influxdbv2 # configs (token, organization, user, password)
    networks:
      - monitoring
    command: --reporting-disabled --engine-path /root/.influxdbv2_engine
    environment:
      INFLUXDB_DEFAULT_ORG: cloudberry
      INFLUXDB_DEFAULT_BUCKET: cloudberry_logs
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: ziemniak
      INFLUXDB_ADMIN_TOKEN: 'W5lZySDF5A1XevbKqIK717PHBxZOD-D0pSkwYu--LmmVYudgPMGJ-a-oOVVjDl_tgjASZ1efAtGZkV6FbVIYUQ=='
