version: '2'

services:
  mongodb-cb:
    image: mongo:4.4.1
    hostname: mongodb-cb
    container_name: mongodb-cb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
