package com.cloudberry.cloudberry.db.common.service;

import com.cloudberry.cloudberry.db.common.data.ParsedLogs;
import com.cloudberry.cloudberry.db.influx.InfluxDefaults;
import com.cloudberry.cloudberry.db.mongo.data.metadata.ExperimentConfiguration;
import com.cloudberry.cloudberry.db.mongo.data.metadata.ExperimentEvaluation;
import com.cloudberry.cloudberry.util.XmlUtils;
import com.influxdb.client.write.Point;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static java.lang.Long.parseLong;

@Slf4j
@Service
@RequiredArgsConstructor
public class LogsParserImpl implements LogsParser<ParsedLogs> {
    @Value("${influx.buckets.default-logs}")
    private String evaluationLogsBucketName;
    private static final String MEASUREMENT_PREFIX = "measurement_";
    private final Map<String, String> keys = Map.of("[WH]", "[W]", "[SH]", "[S]", "[BH]", "[B]");
    //above fields can come from e.g. rest parameter

    private Map<String, String[]> parameters = new HashMap<>();

    @Override
    public List<ParsedLogs> parseMeasurements(String rawLogs) {
        parameters = new HashMap<>();
        ObjectId evaluationId = getEvaluationId();
        var parsedLogs = parseLogs(rawLogs);
        parsedLogs.getPoints()
                .forEach(point -> point.addTag("evaluation_id", evaluationId.toString()));
        parsedLogs.getExperimentEvaluation().setId(evaluationId);
        return List.of(parsedLogs);
    }

    private ObjectId getEvaluationId() {
        return ObjectId.get();
    }

    private ObjectId getExperimentId(Map<String, Object> xmlMap) {
        return ObjectId.get(); //todo find based on map
    }

    private ParsedLogs parseLogs(String rawLogs) {
        String[] logs = rawLogs.split("\n");
        List<Point> evaluationLogs = new LinkedList<>();
        var experimentConfiguration = new ExperimentConfiguration();
        var experimentEvaluation = new ExperimentEvaluation();

        for (int i = 0; i < logs.length; i++) {
            String rawLog = logs[i];
            String[] log = rawLog.trim().split(";");

            String logPrefix = log[0];
            if (keys.containsKey(logPrefix)) {
                saveParametersOrder(logPrefix, log);
            } else if (keys.containsValue(logPrefix)) {
                evaluationLogs.add(getMeasurementPoint(logPrefix, log));
            } else if (rawLog.startsWith("<")) {
                List<String> xmlLogs = new LinkedList<>();
                String tagName = XmlUtils.getTagName(rawLog);
                String closingTag = null;
                while (!tagName.equals(closingTag)) {
                    i++;
                    rawLog = logs[i];
                    xmlLogs.add(rawLog);
                    closingTag = XmlUtils.getClosingTagName(rawLog);
                }
                xmlLogs.remove(rawLog); //remove closing tag from list
                var xmlMap = getXmlMap(xmlLogs);
                experimentConfiguration.setId(ObjectId.get()); // todo make it generated by db, without this its null and evaluation doesnt't have it
                experimentConfiguration.setParameters(xmlMap);
                experimentConfiguration.setExperimentId(getExperimentId(xmlMap));
                experimentConfiguration.setConfigurationFileName(String.valueOf(xmlMap.get("file")));

            } else {
                LogsParserImpl.log.warn("Header {} not parsed", log[0]);
            }
        }
        experimentEvaluation.setConfigurationId(experimentConfiguration.getId());
        experimentEvaluation.setId(getEvaluationId());

        return new ParsedLogs(evaluationLogsBucketName, evaluationLogs, experimentConfiguration, experimentEvaluation);
    }

    private Map<String, Object> getXmlMap(List<String> xmlLogs) {
        return xmlLogs.stream()
                .map(xmlLog -> xmlLog.split("=", 2))
                .collect(
                        Collectors.toMap(
                                log -> log[0].trim(),
                                log -> parseValue(log[1].trim())
                        )
                );
    }

    private Point getMeasurementPoint(String logType, String[] log) {
        Point point = Point.measurement(MEASUREMENT_PREFIX + logType)
                .addFields(getMapFromArrays(parameters.get(logType), log));

        if (parameters.get(logType)[1].equalsIgnoreCase("time")) {
            long time = parseLong(log[1]);
            point.time(time, InfluxDefaults.WRITE_PRECISION);
        }

        return point;
    }

    /**
     * @param log examples:
     *            [WH];TIME;WORKPLACE_ID;POPULATION_SIZE;AVERAGE_FITNESS;STEP_NUMBER;ENERGY_SUM
     *            [SH];TIME;BEST_SOLUTION_SO_FAR;FITNESS_EVALUATIONS
     */
    private void saveParametersOrder(String logType, String[] log) {
        String logKey = keys.get(logType);
        parameters.compute(logKey, (s, fieldNames) -> {
            if (fieldNames == null) {
                return log;
            }
            throw new IllegalArgumentException(String.format("Log with prefix [%s] already specified.", logType));
        });
    }

    private Map<String, Object> getMapFromArrays(String[] keys, String[] values) {
        return IntStream.range(0, keys.length).boxed()
                .collect(Collectors.toMap(i -> keys[i], i -> parseValue(values[i])));
    }

    private Object parseValue(String value) {
        try {
            return Double.parseDouble(value);
        } catch (NumberFormatException e) {
            return value;
        }
    }
}
